spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myboke
    username: postgres
    password: 12345
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 3000

mybatis:
  mapper-locations: classpath:Mapping/*.xml
  type-aliases-package: com.example.allof.Pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换